// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";

export interface CloudInitConfigPart {
    content: pulumi.Input<string>;
    contentType?: pulumi.Input<string>;
    filename?: pulumi.Input<string>;
    mergeType?: pulumi.Input<string>;
}

export interface GetCloudInitConfigPart {
    content: string;
    contentType?: string;
    filename?: string;
    mergeType?: string;
}
