// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as outputs from "../types/output";

export interface CloudInitConfigPart {
    content: string;
    contentType?: string;
    filename?: string;
    mergeType?: string;
}

export interface GetCloudInitConfigPart {
    content: string;
    contentType?: string;
    filename?: string;
    mergeType?: string;
}
