// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CloudInitConfig extends pulumi.CustomResource {
    /**
     * Get an existing CloudInitConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CloudInitConfigState, opts?: pulumi.CustomResourceOptions): CloudInitConfig {
        return new CloudInitConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terraform-template:index/cloudInitConfig:CloudInitConfig';

    /**
     * Returns true if the given object is an instance of CloudInitConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudInitConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudInitConfig.__pulumiType;
    }

    public readonly base64Encode!: pulumi.Output<boolean | undefined>;
    public readonly gzip!: pulumi.Output<boolean | undefined>;
    public readonly parts!: pulumi.Output<outputs.CloudInitConfigPart[]>;
    /**
     * rendered cloudinit configuration
     */
    public /*out*/ readonly rendered!: pulumi.Output<string>;

    /**
     * Create a CloudInitConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CloudInitConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CloudInitConfigArgs | CloudInitConfigState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as CloudInitConfigState | undefined;
            inputs["base64Encode"] = state ? state.base64Encode : undefined;
            inputs["gzip"] = state ? state.gzip : undefined;
            inputs["parts"] = state ? state.parts : undefined;
            inputs["rendered"] = state ? state.rendered : undefined;
        } else {
            const args = argsOrState as CloudInitConfigArgs | undefined;
            if (!args || args.parts === undefined) {
                throw new Error("Missing required property 'parts'");
            }
            inputs["base64Encode"] = args ? args.base64Encode : undefined;
            inputs["gzip"] = args ? args.gzip : undefined;
            inputs["parts"] = args ? args.parts : undefined;
            inputs["rendered"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(CloudInitConfig.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CloudInitConfig resources.
 */
export interface CloudInitConfigState {
    readonly base64Encode?: pulumi.Input<boolean>;
    readonly gzip?: pulumi.Input<boolean>;
    readonly parts?: pulumi.Input<pulumi.Input<inputs.CloudInitConfigPart>[]>;
    /**
     * rendered cloudinit configuration
     */
    readonly rendered?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CloudInitConfig resource.
 */
export interface CloudInitConfigArgs {
    readonly base64Encode?: pulumi.Input<boolean>;
    readonly gzip?: pulumi.Input<boolean>;
    readonly parts: pulumi.Input<pulumi.Input<inputs.CloudInitConfigPart>[]>;
}
