// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * > This content is derived from https://github.com/terraform-providers/terraform-provider-template/blob/master/website/docs/r/dir.html.markdown.
 */
export class Dir extends pulumi.CustomResource {
    /**
     * Get an existing Dir resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DirState, opts?: pulumi.CustomResourceOptions): Dir {
        return new Dir(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terraform-template:index/dir:Dir';

    /**
     * Returns true if the given object is an instance of Dir.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dir {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dir.__pulumiType;
    }

    /**
     * Path to the directory where the templated files will be written.
     */
    public readonly destinationDir!: pulumi.Output<string>;
    /**
     * Path to the directory where the files to template reside.
     */
    public readonly sourceDir!: pulumi.Output<string>;
    /**
     * Variables for interpolation within the template. Note
     * that variables must all be primitives. Direct references to lists or maps
     * will cause a validation error.
     */
    public readonly vars!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a Dir resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DirArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DirArgs | DirState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as DirState | undefined;
            inputs["destinationDir"] = state ? state.destinationDir : undefined;
            inputs["sourceDir"] = state ? state.sourceDir : undefined;
            inputs["vars"] = state ? state.vars : undefined;
        } else {
            const args = argsOrState as DirArgs | undefined;
            if (!args || args.destinationDir === undefined) {
                throw new Error("Missing required property 'destinationDir'");
            }
            if (!args || args.sourceDir === undefined) {
                throw new Error("Missing required property 'sourceDir'");
            }
            inputs["destinationDir"] = args ? args.destinationDir : undefined;
            inputs["sourceDir"] = args ? args.sourceDir : undefined;
            inputs["vars"] = args ? args.vars : undefined;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(Dir.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Dir resources.
 */
export interface DirState {
    /**
     * Path to the directory where the templated files will be written.
     */
    readonly destinationDir?: pulumi.Input<string>;
    /**
     * Path to the directory where the files to template reside.
     */
    readonly sourceDir?: pulumi.Input<string>;
    /**
     * Variables for interpolation within the template. Note
     * that variables must all be primitives. Direct references to lists or maps
     * will cause a validation error.
     */
    readonly vars?: pulumi.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a Dir resource.
 */
export interface DirArgs {
    /**
     * Path to the directory where the templated files will be written.
     */
    readonly destinationDir: pulumi.Input<string>;
    /**
     * Path to the directory where the files to template reside.
     */
    readonly sourceDir: pulumi.Input<string>;
    /**
     * Variables for interpolation within the template. Note
     * that variables must all be primitives. Direct references to lists or maps
     * will cause a validation error.
     */
    readonly vars?: pulumi.Input<{[key: string]: any}>;
}
