// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class File extends pulumi.CustomResource {
    /**
     * Get an existing File resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FileState, opts?: pulumi.CustomResourceOptions): File {
        return new File(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'terraform-template:index/file:File';

    /**
     * Returns true if the given object is an instance of File.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is File {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === File.__pulumiType;
    }

    /**
     * file to read template from
     */
    public readonly filename!: pulumi.Output<string | undefined>;
    /**
     * rendered template
     */
    public /*out*/ readonly rendered!: pulumi.Output<string>;
    /**
     * Contents of the template
     */
    public readonly template!: pulumi.Output<string | undefined>;
    /**
     * variables to substitute
     */
    public readonly vars!: pulumi.Output<{[key: string]: any} | undefined>;

    /**
     * Create a File resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: FileArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FileArgs | FileState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        if (opts && opts.id) {
            const state = argsOrState as FileState | undefined;
            inputs["filename"] = state ? state.filename : undefined;
            inputs["rendered"] = state ? state.rendered : undefined;
            inputs["template"] = state ? state.template : undefined;
            inputs["vars"] = state ? state.vars : undefined;
        } else {
            const args = argsOrState as FileArgs | undefined;
            inputs["filename"] = args ? args.filename : undefined;
            inputs["template"] = args ? args.template : undefined;
            inputs["vars"] = args ? args.vars : undefined;
            inputs["rendered"] = undefined /*out*/;
        }
        if (!opts) {
            opts = {}
        }

        if (!opts.version) {
            opts.version = utilities.getVersion();
        }
        super(File.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering File resources.
 */
export interface FileState {
    /**
     * file to read template from
     */
    readonly filename?: pulumi.Input<string>;
    /**
     * rendered template
     */
    readonly rendered?: pulumi.Input<string>;
    /**
     * Contents of the template
     */
    readonly template?: pulumi.Input<string>;
    /**
     * variables to substitute
     */
    readonly vars?: pulumi.Input<{[key: string]: any}>;
}

/**
 * The set of arguments for constructing a File resource.
 */
export interface FileArgs {
    /**
     * file to read template from
     */
    readonly filename?: pulumi.Input<string>;
    /**
     * Contents of the template
     */
    readonly template?: pulumi.Input<string>;
    /**
     * variables to substitute
     */
    readonly vars?: pulumi.Input<{[key: string]: any}>;
}
