// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

/**
 * Renders a multi-part cloud-init config from source files.
 */
export function getCloudInitConfig(args: GetCloudInitConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetCloudInitConfigResult> {
    return pulumi.runtime.invoke("terraform-template:index/getCloudInitConfig:getCloudInitConfig", {
        "base64Encode": args.base64Encode,
        "gzip": args.gzip,
        "parts": args.parts,
    }, opts);
}

/**
 * A collection of arguments for invoking getCloudInitConfig.
 */
export interface GetCloudInitConfigArgs {
    /**
     * Base64 encoding of the rendered output. Default to `true`
     */
    readonly base64Encode?: boolean;
    /**
     * Specify whether or not to gzip the rendered output. Default to `true`
     */
    readonly gzip?: boolean;
    /**
     * One may specify this many times, this creates a fragment of the rendered cloud-init config file. The order of the parts is maintained in the configuration is maintained in the rendered template.
     */
    readonly parts: { content: string, contentType?: string, filename?: string, mergeType?: string }[];
}

/**
 * A collection of values returned by getCloudInitConfig.
 */
export interface GetCloudInitConfigResult {
    /**
     * The final rendered multi-part cloudinit config.
     */
    readonly rendered: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
