// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";

/**
 * Renders a template from a file.
 */
export function getFile(args?: GetFileArgs, opts?: pulumi.InvokeOptions): Promise<GetFileResult> {
    args = args || {};
    return pulumi.runtime.invoke("terraform-template:index/getFile:getFile", {
        "filename": args.filename,
        "template": args.template,
        "vars": args.vars,
    }, opts);
}

/**
 * A collection of arguments for invoking getFile.
 */
export interface GetFileArgs {
    /**
     * _Deprecated, please use `template` instead_. The filename for
     * the template. Use [path variables](/docs/configuration/interpolation.html#path-variables) to make
     * this path relative to different path roots.
     */
    readonly filename?: string;
    /**
     * The contents of the template. These can be loaded
     * from a file on disk using the [`file()` interpolation
     * function](/docs/configuration/interpolation.html#file_path_).
     */
    readonly template?: string;
    /**
     * Variables for interpolation within the template. Note
     * that variables must all be primitives. Direct references to lists or maps
     * will cause a validation error.
     */
    readonly vars?: {[key: string]: any};
}

/**
 * A collection of values returned by getFile.
 */
export interface GetFileResult {
    /**
     * The final rendered template.
     */
    readonly rendered: string;
    /**
     * id is the provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
}
